WARNING flwr 2024-03-22 11:46:01,052 | logger.py:118 |
        DEPRECATED FEATURE: flwr.client.start_numpy_client() is deprecated.
	Instead, use `flwr.client.start_client()` by ensuring you first call the `.to_client()` method as shown below:
	flwr.client.start_client(
		server_address='<IP>:<PORT>',
		client=FlowerClient().to_client(), # <-- where FlowerClient is of type flwr.client.NumPyClient object
	)
	Using `start_numpy_client()` is deprecated.
        This is a deprecated feature. It will be removed
        entirely in future versions of Flower.
INFO flwr 2024-03-22 11:46:01,082 | grpc.py:52 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2024-03-22 11:46:01,109 | connection.py:55 | ChannelConnectivity.IDLE
DEBUG flwr 2024-03-22 11:46:01,110 | connection.py:55 | ChannelConnectivity.READY













957/957 [==============================] - 29s 29ms/step - loss: 0.0799 - accuracy: 0.9760
161/161 [==============================] - 2s 11ms/step - loss: 0.4413 - accuracy: 0.9486















957/957 [==============================] - 30s 32ms/step - loss: 0.0272 - accuracy: 0.9913
161/161 [==============================] - 1s 8ms/step - loss: 0.1680 - accuracy: 0.9751










593/957 [=================>............] - ETA: 12s - loss: 0.0194 - accuracy: 0.9943





932/957 [============================>.] - ETA: 0s - loss: 0.0172 - accuracy: 0.9950
DEBUG flwr 2024-03-22 11:47:48,662 | connection.py:220 | gRPC channel closed
Traceback (most recent call last):
  File "C:\Users\chinm\Desktop\FL-FINAL\MNIST\client1.py", line 47, in <module>
    fl.client.start_numpy_client(server_address="127.0.0.1:8080", client=MnistClient1())
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\flwr\client\app.py", line 500, in start_numpy_client
    start_client(
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\flwr\client\app.py", line 248, in start_client
    _start_client_internal(
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\flwr\client\app.py", line 361, in _start_client_internal
    message = receive()
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\flwr\client\grpc_client\connection.py", line 132, in receive
    proto = next(server_message_iterator)
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\grpc\_channel.py", line 540, in __next__
    return self._next()
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\grpc\_channel.py", line 949, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connection reset"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:8080 {created_time:"2024-03-22T06:17:37.7015589+00:00", grpc_status:14, grpc_message:"Connection reset"}"

957/957 [==============================] - 31s 33ms/step - loss: 0.0175 - accuracy: 0.9949