2024-03-18 11:13:59,685 INFO    StreamThr :13592 [internal.py:wandb_internal():86] W&B internal server running at pid: 13592, started at: 2024-03-18 11:13:59.685834
2024-03-18 11:13:59,691 DEBUG   HandlerThread:13592 [handler.py:handle_request():146] handle_request: status
2024-03-18 11:13:59,701 INFO    WriterThread:13592 [datastore.py:open_for_write():87] open: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111359-frl7zvqi\run-frl7zvqi.wandb
2024-03-18 11:13:59,702 DEBUG   SenderThread:13592 [sender.py:send():378] send: header
2024-03-18 11:13:59,702 DEBUG   SenderThread:13592 [sender.py:send():378] send: run
2024-03-18 11:14:00,541 INFO    SenderThread:13592 [dir_watcher.py:__init__():211] watching files in: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111359-frl7zvqi\files
2024-03-18 11:14:00,541 INFO    SenderThread:13592 [sender.py:_start_run_threads():1099] run started: frl7zvqi with start time 1710740639.691445
2024-03-18 11:14:00,561 DEBUG   HandlerThread:13592 [handler.py:handle_request():146] handle_request: check_version
2024-03-18 11:14:00,564 DEBUG   SenderThread:13592 [sender.py:send_request():405] send_request: check_version
2024-03-18 11:14:00,747 DEBUG   HandlerThread:13592 [handler.py:handle_request():146] handle_request: run_start
2024-03-18 11:14:01,982 DEBUG   HandlerThread:13592 [system_info.py:__init__():26] System info init
2024-03-18 11:14:01,982 DEBUG   HandlerThread:13592 [system_info.py:__init__():41] System info init done
2024-03-18 11:14:01,982 INFO    HandlerThread:13592 [system_monitor.py:start():194] Starting system monitor
2024-03-18 11:14:01,982 INFO    SystemMonitor:13592 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-03-18 11:14:01,987 INFO    HandlerThread:13592 [system_monitor.py:probe():214] Collecting system info
2024-03-18 11:14:02,001 INFO    SystemMonitor:13592 [interfaces.py:start():190] Started cpu monitoring
2024-03-18 11:14:02,002 INFO    SystemMonitor:13592 [interfaces.py:start():190] Started disk monitoring
2024-03-18 11:14:02,002 INFO    SystemMonitor:13592 [interfaces.py:start():190] Started gpu monitoring
2024-03-18 11:14:02,004 INFO    SystemMonitor:13592 [interfaces.py:start():190] Started memory monitoring
2024-03-18 11:14:02,017 INFO    SystemMonitor:13592 [interfaces.py:start():190] Started network monitoring
2024-03-18 11:14:02,024 DEBUG   HandlerThread:13592 [system_info.py:probe():150] Probing system
2024-03-18 11:14:02,024 DEBUG   HandlerThread:13592 [gitlib.py:_init_repo():56] git repository is invalid
2024-03-18 11:14:02,024 DEBUG   HandlerThread:13592 [system_info.py:probe():198] Probing system done
2024-03-18 11:14:02,024 DEBUG   HandlerThread:13592 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.22631-SP0', 'python': '3.9.13', 'heartbeatAt': '2024-03-18T05:44:02.024062', 'startedAt': '2024-03-18T05:43:59.671982', 'docker': None, 'cuda': None, 'args': ('8000',), 'state': 'running', 'program': 'C:\\Users\\chinm\\Desktop\\FL-FINAL\\MNIST\\server.py', 'codePathLocal': 'server.py', 'codePath': 'server.py', 'host': 'MSI', 'username': 'chinm', 'executable': 'C:\\Users\\chinm\\anaconda3\\New folder\\python.exe', 'cpu_count': 6, 'cpu_count_logical': 12, 'cpu_freq': {'current': 2496.0, 'min': 0.0, 'max': 2496.0}, 'cpu_freq_per_core': [{'current': 2496.0, 'min': 0.0, 'max': 2496.0}], 'disk': {'/': {'total': 458.81444931030273, 'used': 431.2613525390625}}, 'gpu': 'NVIDIA GeForce RTX 3050 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3050 Laptop GPU', 'memory_total': 4294967296}], 'memory': {'total': 7.8259735107421875}}
2024-03-18 11:14:02,024 INFO    HandlerThread:13592 [system_monitor.py:probe():224] Finished collecting system info
2024-03-18 11:14:02,024 INFO    HandlerThread:13592 [system_monitor.py:probe():227] Publishing system info
2024-03-18 11:14:02,024 DEBUG   HandlerThread:13592 [system_info.py:_save_conda():207] Saving list of conda packages installed into the current environment
2024-03-18 11:14:02,033 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:14:02,565 INFO    Thread-16 :13592 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111359-frl7zvqi\files\conda-environment.yaml
2024-03-18 11:14:04,711 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:04,711 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:07,384 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:07,384 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:10,034 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:10,040 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:12,699 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:12,700 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:15,393 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:15,393 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:18,161 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:18,161 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:20,904 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:20,904 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:23,587 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:23,587 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:23,704 INFO    Thread-16 :13592 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111359-frl7zvqi\files\conda-environment.yaml
2024-03-18 11:14:23,991 DEBUG   HandlerThread:13592 [system_info.py:_save_conda():219] Saving conda packages done
2024-03-18 11:14:23,991 INFO    HandlerThread:13592 [system_monitor.py:probe():229] Finished publishing system info
2024-03-18 11:14:24,023 DEBUG   HandlerThread:13592 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:14:24,023 DEBUG   HandlerThread:13592 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:14:24,023 DEBUG   HandlerThread:13592 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:14:24,023 DEBUG   HandlerThread:13592 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:14:24,023 DEBUG   HandlerThread:13592 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:14:24,023 DEBUG   HandlerThread:13592 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:14:24,023 DEBUG   HandlerThread:13592 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:14:24,023 DEBUG   HandlerThread:13592 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:14:24,023 DEBUG   SenderThread:13592 [sender.py:send():378] send: files
2024-03-18 11:14:24,023 INFO    SenderThread:13592 [sender.py:_save_file():1365] saving file wandb-metadata.json with policy now
2024-03-18 11:14:24,821 INFO    Thread-16 :13592 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111359-frl7zvqi\files\wandb-metadata.json
2024-03-18 11:14:25,036 DEBUG   HandlerThread:13592 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:14:25,991 DEBUG   HandlerThread:13592 [handler.py:handle_request():146] handle_request: python_packages
2024-03-18 11:14:25,991 DEBUG   SenderThread:13592 [sender.py:send_request():405] send_request: python_packages
2024-03-18 11:14:25,991 DEBUG   HandlerThread:13592 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:14:25,999 DEBUG   HandlerThread:13592 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:14:25,999 DEBUG   SenderThread:13592 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:14:26,003 INFO    wandb-upload_0:13592 [upload_job.py:push():131] Uploaded file C:\Users\chinm\AppData\Local\Temp\tmpaidrhqtxwandb\7rrp34be-wandb-metadata.json
2024-03-18 11:14:26,250 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:26,251 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:26,321 DEBUG   SenderThread:13592 [sender.py:send():378] send: telemetry
2024-03-18 11:14:26,832 INFO    Thread-16 :13592 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111359-frl7zvqi\files\requirements.txt
2024-03-18 11:14:26,832 INFO    Thread-16 :13592 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111359-frl7zvqi\files\output.log
2024-03-18 11:14:28,854 INFO    Thread-16 :13592 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111359-frl7zvqi\files\output.log
2024-03-18 11:14:28,948 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:28,948 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:30,369 DEBUG   HandlerThread:13592 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:14:30,881 INFO    Thread-16 :13592 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111359-frl7zvqi\files\config.yaml
2024-03-18 11:14:31,604 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:31,610 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:34,261 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:34,261 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:35,704 DEBUG   HandlerThread:13592 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:14:36,911 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:36,911 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:39,566 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:39,566 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:40,743 DEBUG   HandlerThread:13592 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:14:41,011 DEBUG   HandlerThread:13592 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:14:41,011 DEBUG   HandlerThread:13592 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:14:41,016 DEBUG   SenderThread:13592 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:14:42,292 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:42,292 ERROR   gpu       :13592 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:14:44,127 INFO    memory    :13592 [interfaces.py:monitor():140] Process proc.memory.rssMB has exited.
2024-03-18 11:14:44,127 DEBUG   SystemMonitor:13592 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-03-18 11:14:44,127 DEBUG   SystemMonitor:13592 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-03-18 11:14:44,127 DEBUG   SystemMonitor:13592 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-03-18 11:14:44,127 DEBUG   SenderThread:13592 [sender.py:send():378] send: stats
2024-03-18 11:14:44,772 ERROR   gpu       :13592 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-18 11:14:46,063 INFO    MainThread:13592 [internal.py:handle_exit():76] Internal process exited
2024-03-18 11:14:46,151 DEBUG   HandlerThread:13592 [handler.py:handle_request():146] handle_request: status_report
